### ISSUE TITLE
ZodError when running nested job when PR is closed

### ISSUE THREAD

**Issue by onish-ai** [qoomon/actions--access-token#122]
I am trying to get an access token for two repos using the owner config however I am encountering the following error when the action is ran:
```json
Error: ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      1
    ],
    "message": "Expected string, received null"
  }
]
    at get error [as error] (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:57776:31)
    at ZodDefault.parse (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:57881:22)
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61513:14
    at runAction (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:57155:5)
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61505:1
Error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      1
    ],
    "message": "Expected string, received null"
  }
]
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:616[12](https://github.com/actions/runs/11407566039/job/31743874029#step:2:13):3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:3[16](https://github.com/actions/runs/11407566039/job/31743874029#step:2:17):24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ]
}
```

The access token is running in a nested job (using a workflow call) and the workflow file looks something like this:
```yaml
name: Failing Job

on:
  workflow_call:
    inputs:
      version: 
        description: "Version"
        required: true
        type: string
      repository_name:
        description: "Name of the repository"
        required: true
        type: string

jobs:
  failing_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get Access Token
        uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          repositories: |
            - CURRENT_REPO
            - ${{ github.event.inputs.repository_name }}
          scope: owner
          permissions: |
            contents: write
            pull-requests: write

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          repository: ORG/${{ github.event.inputs.repository_name }}
          ref: main
          submodules: recursive
          fetch-depth: 0
          token: ${{ steps.access-token.outputs.token }}
```

The workflow that is calling the job looks like this:
```yaml
name: Release

on:
    workflow_dispatch:
    pull_request:
      types:
        - closed
      branches:
        - main

jobs:
  release_workflow:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_workflow.outputs.version }}
    steps:
      - name: Set Checkout Ref
        id: set_ref
        run: echo "ref=${{ github.event_name == 'workflow_dispatch' && 'develop' || github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.ref }}
  
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true

      - name: Get Access Token for gitflow-action
        uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
              contents: write
              pull-requests: write

      - id: release_workflow
        name: release_workflow
        uses: RELEASE_ACTION
        with:
          develop_branch: "develop"
          main_branch: "main"
          merge_back_from_main: true
          version: ${{ env.majorMinorPatch }}
        env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}

  call_failing_job:
    uses: ./.github/workflows/FAILING_JOB.yml
    if: ${{ github.event.pull_request.merged == true }}
    needs: release_workflow
    permissions:
      id-token: write
    secrets: inherit
    with:
      version: ${{ needs.release_workflow.outputs.version }}
      repository_name: "SOME_REPO"

```

I am currently using the owner config as shown below, this is stored in `ORG/.github-access-token/access-token.yaml`.
```yaml
origin: ORG/.github-access-token # e.g. qoomon/.github-access-token

# Configure which subjects are allowed to request an access token.
# allowed-subjects:
#   - 'repo:ORIGIN_OWNER/*:**' # Default
#
# === Allowed Subject Pattern Wildcards ===
#
# '*' - match every character except ':'
# ':**' - match every following claim, can only be used at the end of a subject pattern

# Configuration which permissions are allowed to be managed by the repositories themselves
allowed-repository-permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
  # === Repository permissions ===
  #
  # actions: read # read or write
  # actions-variables: read # read or write
  # administration: read # read or write - BE AWARE 'administration' scope can not be completely limited to a repository e.g. create new repositories is still possible
  # checks: read # read or write
  # codespaces: read # read or write
  # codespaces-lifecycle-admin: read # read or write
  # codespaces-metadata: read # read or write
  # codespaces-secrets: read # write
  contents: write # read or write
  # custom-properties: read # read or write
  # dependabot-secrets: read # read or write
  # deployments: read # read or write
  # discussions: read # read or write
  # environments: read # read or write
  # issues: read # read or write
  # merge-queues: read # read or write
  # packages: read # read or write
  # pages: read # read or write
  # projects: read # read or write or admin
  pull-requests: write # read or write
  # repository-advisories: read # read or write
  # repository-hooks: read # read or write
  # repository-projects: read # read or write or admin
  # secret-scanning-alerts: read # read or write
  # secrets: read # read or write
  # security-events: read # read or write
  # statuses: read # read or write
  # team-discussions: read # read or write
  # vulnerability-alerts: read # read or write
  # workflows: write # only write

# Grant owner scoped permissions (owner permission or owner wide repository permissions)
# NOTE: Every statement will always implicitly grant `metadata: read` permission.
statements:
  - subjects:
    # === Subject Pattern examples ===
    #
    # grant access to jobs running on the main branch
    - repo:*:ref:refs/heads/main
    # grant access to jobs running on the develop branch
    - repo:*:ref:refs/heads/develop
    # grant access to jobs running in a pull request
    - repo:*:pull_request
    # grant access jobs running on any tag starting with a v
    # - repo:${origin}:ref:refs/tags/v*
    # grant access to jobs using production environment
    # - repo:${origin}:environment:production
    # grant access to jobs of a specific workflow file
    # - repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    # === Subject Pattern Variables and Wildcards ===
    #
    # ${origin} - resolves to the origin repository name e.g. qoomon/sandbox
    # '*' - match every character except ':'
    # ':**' - match every following claim, can only be used at the end of a subject pattern

    # === GitHub Actions OIDC Token Subjects ===
    #
    # A GitHub Actions job will always have the following subjects
    # The original OIDC token 'sub' claim e.g. repo:${origin}:ref:refs/heads/main or repo:${origin}:environment:production
    # repo:${origin}:ref:<ref> e.g. repo:${origin}:ref:refs/heads/main
    # repo:${origin}:environment:<environment> e.g. repo:${origin}:environment:production
    # repo:${origin}:workflow_ref:<workflow_ref> e.g. repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main
    # repo:${origin}:job_workflow_ref:<job_workflow_ref> e.g. repo:${origin}:job_workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
      # === Organization permissions ===
      # members: read # read or write
      # organization-actions-variables: read # read or write
      # organization-administration: read # read or write
      # organization-announcement-banners: read # read or write
      # organization-codespaces: read # read or write
      # organization-codespaces-secrets: read # read or write
      # organization-codespaces-settings: read # read or write
      # organization-copilot-seat-management: read # read or write
      # organization-custom-org-roles: read # read or write
      # organization-custom-properties: read read # read or write or admin
      # organization-custom-roles: read # read or write
      # organization-dependabot-secrets: read # read or write
      # organization-events: read # only read
      # organization-hooks: read # read or write
      # organization-personal-access-token-requests: read # read or write
      # organization-personal-access-tokens: read # read or write
      # organization-plan: read # only read
      # organization-projects: read # read or write or admin
      # organization-secrets: read # read or write
      # organization-self-hosted-runners: read # read or write
      # organization-user-blocking: read # read or write

      # === Repository permissions ===
      #
      # actions: read # read or write
      # actions-variables: read # read or write
      # administration: read # read or write - BE AWARE 'administration' scope can not be completely limited to a repository e.g. create new repositories is still possible
      # checks: read # read or write
      # codespaces: read # read or write
      # codespaces-lifecycle-admin: read # read or write
      # codespaces-metadata: read # read or write
      # codespaces-secrets: read # write
      contents: write # read or write
      # custom-properties: read # read or write
      # dependabot-secrets: read # read or write
      # deployments: read # read or write
      # discussions: read # read or write
      # environments: read # read or write
      # issues: read # read or write
      # merge-queues: read # read or write
      # packages: read # read or write
      # pages: read # read or write
      # projects: read # read or write or admin
      pull-requests: write # read or write
      # repository-advisories: read # read or write
      # repository-hooks: read # read or write
      # repository-projects: read # read or write or admin
      # secret-scanning-alerts: read # read or write
      # secrets: read # read or write
      # security-events: read # read or write
      # statuses: read # read or write
      # team-discussions: read # read or write
      # vulnerability-alerts: read # read or write
      # workflows: write # only write
```

As mentioned, the action is failing when it is ran after a PR is closed, but it is worth noting that the action runs fine when calling it using a workflow dispatch (not in a nested job).
