### ISSUE TITLE
Invalid access policy

### ISSUE THREAD

**Issue by captainmoose** [qoomon/actions--access-token#184]
Hi there, I am getting Invalid access policy when trying to access a target repo (repoB) to get its content token.  I am using actions-access-token to get the token in my action in requesting repo (repoA) to pass on to a dockerfile as a env variable for the target repo which needs to be included in the image through a curl call:

`curl -L \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \ ...`

I created the owner repo under <my_org>/<.github-access-token> with an access-token.yml file that looks like this:

`origin: <my_org>/.github-access-token
   - 'repo:bavirtual/*:**' # Default
allowed-repository-permissions:
  contents: read # read or write
statements:
  - subjects:
    - repo:${origin}:ref:refs/heads/main
    - repo:${origin}:ref:refs/tags/v*
    - repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    repo:${origin}:ref:refs/heads/main
    repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main  
    repo:${origin}:job_workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    permissions:
      contents: read # read or write`

I also created  an .github/access-token.yml file in the target repository repoB that looks like this:

`origin: <my_org>/<repoA>
statements:
  - subjects:
      - repo:${origin}:ref:refs/heads/main
      - repo:${origin}:ref:refs/tags/v*
      - repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

      repo:${origin}:ref:refs/heads/main
      repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main
      repo:${origin}:job_workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    permissions:
      contents: read # read or write`

The action in the requesting repo repoA looks something like this:

`name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: <img_name>

permissions: read-all

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'push'

    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          repository: <my_org>/<repoB>
          permissions: |
            contents: read

      - name: Build image
        run: docker build . --file Dockerfile --tag image
        env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}`

What are the required permissions from the template are a bit vague, so I went with most subjects and contents read which is what I need from the token access to repoB.

Thanks,
Mustafa

**Comment by qoomon** [comment]
`allowed-subjects:`was missing in your org policy

```yaml
origin: <my_org>/.github-access-token
allowed-subjects:
   - 'repo:<my_org>/*:**'
allowed-repository-permissions:
  contents: read
statements:
  - subjects:
    - repo:${origin}:ref:refs/heads/main
    - repo:${origin}:ref:refs/tags/v*
    - repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

    permissions:
      contents: read
```

**Comment by qoomon** [comment]
btw your `allowed-subjects:` is the default value

```yaml
allowed-subjects:
   - 'repo:<my_org>/*:**'
```

**Comment by captainmoose** [comment]
Thanks, it's always the small things.  
I just did that but still getting the error.  

Now the "origin: " should always be the repo itself (i.e. for RepoA, the access-token.ym file should read "origin: <my_org>/RepoA" correct?

Also, do I need the .github/access-token.yml in both RepoA and RepoB or just RepoB, the granting repo? and should the subject referring to the workflow should always map to build.yml or my own actions file dockerpublish.yml?

**Comment by qoomon** [comment]
> Thanks, it's always the small things.

:-D

**Comment by qoomon** [comment]
the `Effective OIDC token subjects:` from the error shows you what subjects you probably need to grant access for in repo **B** (you don't need to add all, just one of the subjects that makes most sense for your use case)

**Comment by captainmoose** [comment]
Great, it is working fine now and I am getting the token for repo_B.  However, I am back to the same issue that got me to install your GH App.  The curl is still failing, how can I make sure the GITHUB_TOKEN is new token and not the default GH Actions token:

````
curl -L \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \ 
    https://github.com/<my_org>/<repo_B>/archive/refs/heads/main.tar.gz
````

Also, once I get this to work, would this token work for RepoC if I do the same as I did in RepoB access-token.yml?

**Comment by qoomon** [comment]
```yaml
   steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
              contents: read

      - name: Update secret
         run: |
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://github.com/<my_org>/<repo_B>/archive/refs/heads/main.tar.gz
        env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}
```
