### ISSUE TITLE
Trigger workflow repo HTTP 404: Not Found

### ISSUE THREAD

**Issue by captainmoose** [qoomon/actions--access-token#198]
Hi again,

I am trying to do the same as in your example for Trigger a Workflow.  I am getting the token but I am getting a 404, and I was wondering whether it is related to the token not being valid.  Here is how the workflow looks like:

````yaml
name: Trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
            actions: write

      - name: Trigger workflow
        run: >-
          gh workflow
          run dockerpublish.yml
          --repo <my_org>/<target_repo>
          --ref main
          --field logLevel=debug
        env:
          GITHUB_TOKEN: ${{steps.access-token.outputs.token}}
````

The error I'm getting in GH Actions is:

````bash
Run gh workflow run dockerpublish.yml --repo <my_org>/<target_repo> --ref main --field logLevel=debug
HTTP 404: Not Found (https://api.github.com/repos/<my_org>/<target_repo>/actions/workflows/dockerpublish.yml)
Error: Process completed with exit code [1](https://github.com/<my_org>/<target_repo>/actions/runs/12034310818/job/33553492291#step:3:1).
````

I ran the `gh workflow run dockerpublish.yml --repo <my_org>/<target_repo> --ref main` from command prompt after a `gh auth login` and it ran fine.

**Comment by qoomon** [comment]
Is the target repo `<my_org>/<target_repo>` the same repository where the workflow you prodied runs in?

**Comment by qoomon** [comment]
If not you need to create a token for that target repository. By default a token for the repository of the workflow is requested.
So you might need to request the token for the target repository like this
```yaml
     - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          repository: <my_org>/<target_repo>
          permissions: |
            actions: write
```
