### ISSUE TITLE
Can't make the action work

### ISSUE THREAD

**Issue by irizzant** [qoomon/actions--access-token#56]
Hello
I have an org in which I created the repo
ORG/.github-access-token

In this repo I created a .github/access-token.yaml file with:
```yaml
origin: ORG/.github-access-token
allowed-repository-permissions:
 secrets: write
```
Then I have another repo:
ORG/test
with a workflow defined as:
```yaml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
              secrets: write

      - name: Update secret
        run: >- 
          gh secret 
          set 'API_KEY' 
          --body "$(date +%s)" 
          --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}

  read-secret:
    needs: update-secret
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.API_KEY }}
```

It keeps failing with:
```
Run qoomon/actions--access-token@v3
Get access token...
Error: HttpClientError: Issues:
Error: Issues:
- ORG:
  - Access policy not found
Effective OIDC token subjects:
- repo:ORG/test:ref:refs/heads/main
- repo:ORG/test:workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main
- repo:ORG/test:job_workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main
- ORG:
  - Access policy not found
Effective OIDC token subjects:
- repo:ORG/test:ref:refs/heads/main
- repo:ORG/test:workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main
- repo:ORG/test:job_workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main
    at file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61467:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async httpRequest (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61455:12)
    at async getAccessToken (file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61431:12)
    at async file:///home/runner/work/_actions/qoomon/actions--access-token/v3/action/dist/main/index.js:61389:25 {
  statusCode: 403,
  result: {
    requestId: '6f2d7923-ce44-450a-a70c-ee0d4f9d0a5b',
    status: 403,
    error: 'Forbidden',
    message: 'Issues:\n' +
      '- ORG:\n' +
      '  - Access policy not found\n' +
      'Effective OIDC token subjects:\n' +
      '- repo:ORG/test:ref:refs/heads/main\n' +
      '- repo:ORG/test:workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main\n' +
      '- repo:ORG/test:job_workflow_ref:ORG/test/.github/workflows/workflow.yml@refs/heads/main'
  }
}
```

**Comment by qoomon** [comment]
`allowed-repository-permissions:` only defines which permissions can be managed by repository policy files.

You have two options:
1.  You create a [repository policy file](https://github.com/qoomon/actions--access-token/blob/main/action/docs/access-token.repo-template.yaml) as well (`.github/access-token.yaml`) in the repository where you want to write secrets.
    ```yaml
    origin: ORG/REPO

    statements:
      - subjects:
           repo:${origin}:ref:refs/heads/main # allow access from action runs from main branch
         permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
           secrets: write
    ```
2. You can grant the permissions by the owner policy, however by the owner policy you allow secrets write permission to all ORG repositories for the specific subject.
    ```yaml
    # ...
    statements:
      - subjects:
           repo:ORG/REPO:ref:refs/heads/main # allow access from action runs from main branch
         permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
           secrets: write
    ```
    workflow usage:
    ```yaml
     - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          scope: owner
          permissions: |
              secrets: write
    ```

**Comment by irizzant** [comment]
Thanks for the update @qoomon 

I have the repo:
ORG/.github-access-token

In this repo I have a .github/access-token.yaml file with:
```yaml
origin: ORG/.github-access-token
allowed-repository-permissions:
  secrets: write
```

I went with option 1. for repo
ORG/test

I created a .github/access-token.yaml in this repo with:
```yaml
origin: ORG/test
statements:
  - subjects:
    - repo:${origin}:ref:refs/heads/main
    permissions:
      secrets: write
```

Still the same error as above
